version: '3.8'

services:
  bankist:
    image: nginx:latest
    container_name: Bankist-App-Container
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ../src:/var/www/
      - ./nginx:/etc/nginx/conf.d
